/** Built-in task templates. Name and prompt follow the UI locale at the moment a chip is picked. */

import type { Locale } from "./i18n/messages";

export interface BuiltinTaskTemplate {
  id: string;
  name: string;
  prompt: string;
}

const zhHant: readonly BuiltinTaskTemplate[] = [
  {
    id: "wool",
    name: "媷羊毛與福利",
    prompt: [
      "判斷這則訊息是否符合下列薅羊毛／福利收錄，且沒有觸及剔除標準。",
      "沒有地區限制、或亞洲地區用戶也能參加的都算；只限香港的產品都算，因為香港屬於亞洲；排除亞洲的優惠不算。",
      "",
      "【收錄類別】",
      "1. 信用卡/扣帳卡：新卡優惠、高額回贈（cashback）、里數/積分優惠、免年費條件",
      "2. 銀行：開戶獎賞、存款利率優惠、跨境轉帳優惠",
      "3. 支付工具（支付寶/AlipayHK/WeChat Pay/Octopus/PayMe 等）：新用戶優惠、商戶折扣、儲值獎賞；其他全球或亞洲支付工具的同類福利都算",
      "4. Staking/持幣：主流幣（BTC/ETH/SOL 等）staking 年化（APY）、鎖倉條件、平台可信度",
      "5. Web3 定存/理財福利：CeFi/DeFi 定存產品、年化收益、平台風險評級",
      "6. 新出信用卡/扣帳卡（APY 型或高反現）：例如虛擬銀行、金融科技卡發行的高息/高反現產品",
      "7. eSIM/電話卡：平價保號方案、漫遊套餐優惠，沒有地區限制、或亞洲用戶都能買的都算",
      "8. 鏈上身份福利：例如錢包地址持有記錄、鏈上活動證明（POAP 等）帶來的白名單/空投資格",
      "9. NFT：低價/免費獲取、未來有實際效用或回報預期的項目（非純炒作）",
      "10. 新鏈活動/空投：新公鏈測試網任務、生態活動，沒有地區限制、或亞洲用戶都能參加的都算",
      "",
      "【剔除標準】",
      "- 需要先存入大額資金才有資格的（高風險局）",
      "- 平台未經審核/上線少於 3 個月/無審計報告的 DeFi 或交易所",
      "- 需要洩露 KYC/身分證資料換取小額回饋",
      "- 明顯是推薦碼/傳銷式獎賞結構（拉人頭才有回報）",
      "- 過期或即將過期（少於 48 小時）的優惠，除非特別註明「急件」",
      "",
      "無關閒聊、純價格波動、重複轉發不算。",
    ].join("\n"),
  },
  {
    id: "crypto-major",
    name: "crypto重大消息",
    prompt: [
      "判斷這則訊息是否為加密貨幣的重大消息，且沒有觸及剔除標準。",
      "",
      "【收錄類別】",
      "1. 主流幣或重要協議的劇烈漲跌",
      "2. 交易所故障或倒閉",
      "3. 監管或 ETF 決定",
      "4. 大型駭客",
      "5. 脫錨",
      "6. 主流鏈停擺",
      "",
      "【剔除標準】",
      "- 日常小幅波動",
      "- 迷因幣喊單",
      "- 沒有新事實的轉發",
      "",
      "無關閒聊、純價格波動、重複轉發不算。",
    ].join("\n"),
  },
  {
    id: "cloud-resident",
    name: "雲居民福利資訊",
    prompt: [
      "判斷這則訊息是否是給雲居民的福利或實用資訊，且寫明了領取方式，而且沒有觸及剔除標準。",
      "",
      "【收錄類別】",
      "1. 優惠",
      "2. 免費額度",
      "3. 補貨",
      "4. 邀請獎勵",
      "5. 節點",
      "6. 白名單",
      "以上每一項都要附上明確的領取方式才算。",
      "",
      "【剔除標準】",
      "- 與雲居民福利無關的閒聊",
      "- 其他專案",
      "- 沒有領取方式的宣傳",
      "",
      "無關閒聊、純價格波動、重複轉發不算。",
    ].join("\n"),
  },
  {
    id: "stock-directional",
    name: "{某股票}的利好消息或負面消息",
    prompt: [
      "使用者會把名稱和本段裡的「某股票」換成要追蹤的股票代碼或公司名。判斷這則訊息是否在談這檔股票，而且同時給出利好或負面原因，且沒有觸及剔除標準。",
      "",
      "【收錄類別】",
      "1. 利好，並且點名這檔股票：業績、訂單、政策支持、增持、上調",
      "2. 負面，並且點名這檔股票：虧損、調查、減持、下調、事故、訴訟",
      "股票代碼或公司名，以及上面其中一個原因，必須同時出現。",
      "",
      "【剔除標準】",
      "- 其他股票",
      "- 沒有方向的純行情",
      "- 無關大盤閒聊",
      "",
      "無關閒聊、純價格波動、重複轉發不算。",
    ].join("\n"),
  },
  {
    id: "airdrop-testnet",
    name: "空投與測試網",
    prompt: [
      "判斷這則訊息是否為還能參與的空投、測試網、互動任務或積分活動，且沒有觸及剔除標準。",
      "",
      "【收錄類別】",
      "1. 還能參加的空投",
      "2. 還能參加的測試網",
      "3. 還能參加的互動任務",
      "4. 還能參加的積分活動",
      "做法、時間、連結至少要有一項。",
      "",
      "【剔除標準】",
      "- 已結束的活動",
      "- 純喊單",
      "- 沒有參加方式的貼文",
      "",
      "無關閒聊、純價格波動、重複轉發不算。",
    ].join("\n"),
  },
  {
    id: "exchange-listing",
    name: "交易所上幣與下架",
    prompt: [
      "判斷這則訊息是否為交易所的上幣、開盤、下架、暫停充提或交易對變更，且沒有觸及剔除標準。必須點名幣種或交易對。",
      "",
      "【收錄類別】",
      "1. 新上幣",
      "2. 開盤",
      "3. 下架",
      "4. 暫停充提",
      "5. 交易對變更",
      "以上每一項都要點名幣種或交易對。",
      "",
      "【剔除標準】",
      "- 沒有點名對象的泛稱行情",
      "",
      "無關閒聊、純價格波動、重複轉發不算。",
    ].join("\n"),
  },
  {
    id: "scam-alert",
    name: "詐騙與安全警訊",
    prompt: [
      "判斷這則訊息是否在警告下列安全事件，且沒有觸及剔除標準。必須有具體對象或手法。",
      "",
      "【收錄類別】",
      "1. 詐騙",
      "2. 釣魚",
      "3. 假空投",
      "4. 盜幣",
      "5. 私鑰外洩",
      "6. 惡意授權",
      "7. 合約風險",
      "以上每一項都要點名具體對象或手法。",
      "",
      "【剔除標準】",
      "- 沒有對象的泛泛提醒",
      "",
      "無關閒聊、純價格波動、重複轉發不算。",
    ].join("\n"),
  },
  {
    id: "account-speaks",
    name: "{某帳號}發話",
    prompt: [
      "使用者會把名稱和本段裡的「某帳號」換成要追蹤的人、公司或頻道，並把「某主題」換成要聽的主題。判斷這則訊息是否是該帳號本人在發話，而且內容符合該主題，且沒有觸及剔除標準。",
      "",
      "【收錄類別】",
      "1. 發話者就是指定的那個帳號（人、公司或頻道）",
      "2. 內容符合使用者寫下的主題",
      "兩項必須同時成立才算。",
      "",
      "【剔除標準】",
      "- 同一個聊天裡其他人的發言，即使話題相同也不算",
      "- 該帳號的打招呼、貼圖",
      "- 該帳號沒有實質內容的轉發",
      "",
      "無關閒聊、純價格波動、重複轉發不算。",
    ].join("\n"),
  },
  {
    id: "actionable-howto",
    name: "可照做的做法",
    prompt: [
      "判斷這則訊息是否包含可以照做、並且能做完一件具體事情的做法，且沒有觸及剔除標準。",
      "",
      "【收錄類別】",
      "1. 步驟：按著做就能完成一件具體事情",
      "2. 指令：執行後就能完成一件具體事情",
      "3. 設定：改完就能完成一件具體事情",
      "4. 一條連結：打開後就能完成那件具體事情",
      "步驟、指令、設定、連結至少要有一項。",
      "",
      "【剔除標準】",
      "- 只有意見，沒有做法",
      "- 純新聞，沒有做法",
      "- 沒有做法的轉發",
      "",
      "無關閒聊、純價格波動、重複轉發不算。",
    ].join("\n"),
  },
  {
    id: "hiring",
    name: "徵人、接案或合作",
    prompt: [
      "判斷這則訊息是否在徵人、接案或找合作，且沒有觸及剔除標準。必須同時點名角色或技能，以及聯絡方式或連結。",
      "",
      "【收錄類別】",
      "1. 徵人：點名職位或技能，並附上聯絡方式或連結",
      "2. 接案：點名要做的角色或技能，並附上聯絡方式或連結",
      "3. 合作：點名需要的角色或技能，並附上聯絡方式或連結",
      "",
      "【剔除標準】",
      "- 沒有聯絡方式或連結的勵志貼文",
      "- 沒有點名角色或技能的貼文",
      "",
      "無關閒聊、純價格波動、重複轉發不算。",
    ].join("\n"),
  },
  {
    id: "tech-ai",
    name: "科技與 AI",
    prompt: [
      "判斷這則訊息是否是給開發者留意的最新科技或 AI 消息，而且帶有新事實，且沒有觸及剔除標準。必須點名專案、模型、函式庫或論文。",
      "",
      "【收錄類別】",
      "1. 模型或 API 發布：點名模型或 API，並寫出新事實",
      "2. 框架或程式語言發布：點名框架或語言，並寫出新事實",
      "3. 開發者必須套用的安全修補：點名專案或函式庫，並寫出要修什麼",
      "4. 破壞性變更：點名專案、框架或 API，並寫出改了什麼",
      "5. 有實際結果的重要論文或基準測試：點名論文或基準，並寫出結果",
      "6. 工具停擺或恢復：點名產品，並寫出停擺或恢復",
      "以上每一項都要有新事實，而且點名專案、模型、函式庫或論文。",
      "",
      "【剔除標準】",
      "- 沒有新事實的炒作",
      "- 價格討論",
      "- 迷因幣",
      "- 空泛的「AI 好厲害」",
      "- 重複轉發",
      "- 無關閒聊",
      "",
      "無關閒聊、純價格波動、重複轉發不算。",
    ].join("\n"),
  },
];

const zhHans: readonly BuiltinTaskTemplate[] = [
  {
    id: "wool",
    name: "薅羊毛与福利",
    prompt: [
      "判断这则消息是否符合下列薅羊毛／福利收录，且没有触及剔除标准。",
      "没有地区限制、或亚洲地区用户也能参加的都算；只限香港的产品都算，因为香港属于亚洲；排除亚洲的优惠不算。",
      "",
      "【收录类别】",
      "1. 信用卡/扣账卡：新卡优惠、高额回赠（cashback）、里数/积分优惠、免年费条件",
      "2. 银行：开户奖赏、存款利率优惠、跨境转账优惠",
      "3. 支付工具（支付宝/AlipayHK/WeChat Pay/Octopus/PayMe 等）：新用户优惠、商户折扣、储值奖赏；其他全球或亚洲支付工具的同类福利都算",
      "4. Staking/持币：主流币（BTC/ETH/SOL 等）staking 年化（APY）、锁仓条件、平台可信度",
      "5. Web3 定存/理财福利：CeFi/DeFi 定存产品、年化收益、平台风险评级",
      "6. 新出信用卡/扣账卡（APY 型或高反现）：例如虚拟银行、金融科技卡发行的高息/高反现产品",
      "7. eSIM/电话卡：平价保号方案、漫游套餐优惠，没有地区限制、或亚洲用户都能买的都算",
      "8. 链上身份福利：例如钱包地址持有记录、链上活动证明（POAP 等）带来的白名单/空投资格",
      "9. NFT：低价/免费获取、未来有实际效用或回报预期的项目（非纯炒作）",
      "10. 新链活动/空投：新公链测试网任务、生态活动，没有地区限制、或亚洲用户都能参加的都算",
      "",
      "【剔除标准】",
      "- 需要先存入大额资金才有资格的（高风险局）",
      "- 平台未经审核/上线少于 3 个月/无审计报告的 DeFi 或交易所",
      "- 需要泄露 KYC/身份证资料换取小额回馈",
      "- 明显是推荐码/传销式奖赏结构（拉人头才有回报）",
      "- 过期或即将过期（少于 48 小时）的优惠，除非特别注明「急件」",
      "",
      "无关闲聊、纯价格波动、重复转发不算。",
    ].join("\n"),
  },
  {
    id: "crypto-major",
    name: "crypto重大消息",
    prompt: [
      "判断这则消息是否为加密货币的重大消息，且没有触及剔除标准。",
      "",
      "【收录类别】",
      "1. 主流币或重要协议的剧烈涨跌",
      "2. 交易所故障或倒闭",
      "3. 监管或 ETF 决定",
      "4. 大型黑客",
      "5. 脱锚",
      "6. 主流链停摆",
      "",
      "【剔除标准】",
      "- 日常小幅波动",
      "- 迷因币喊单",
      "- 没有新事实的转发",
      "",
      "无关闲聊、纯价格波动、重复转发不算。",
    ].join("\n"),
  },
  {
    id: "cloud-resident",
    name: "云居民福利资讯",
    prompt: [
      "判断这则消息是否是给云居民的福利或实用信息，且写明了领取方式，而且没有触及剔除标准。",
      "",
      "【收录类别】",
      "1. 优惠",
      "2. 免费额度",
      "3. 补货",
      "4. 邀请奖励",
      "5. 节点",
      "6. 白名单",
      "以上每一项都要附上明确的领取方式才算。",
      "",
      "【剔除标准】",
      "- 与云居民福利无关的闲聊",
      "- 其他项目",
      "- 没有领取方式的宣传",
      "",
      "无关闲聊、纯价格波动、重复转发不算。",
    ].join("\n"),
  },
  {
    id: "stock-directional",
    name: "{某股票}的利好消息或负面消息",
    prompt: [
      "使用者会把名称和本段里的「某股票」换成要追踪的股票代码或公司名。判断这则消息是否在谈这档股票，而且同时给出利好或负面原因，且没有触及剔除标准。",
      "",
      "【收录类别】",
      "1. 利好，并且点名这档股票：业绩、订单、政策支持、增持、上调",
      "2. 负面，并且点名这档股票：亏损、调查、减持、下调、事故、诉讼",
      "股票代码或公司名，以及上面其中一个原因，必须同时出现。",
      "",
      "【剔除标准】",
      "- 其他股票",
      "- 没有方向的纯行情",
      "- 无关大盘闲聊",
      "",
      "无关闲聊、纯价格波动、重复转发不算。",
    ].join("\n"),
  },
  {
    id: "airdrop-testnet",
    name: "空投与测试网",
    prompt: [
      "判断这则消息是否为还能参与的空投、测试网、互动任务或积分活动，且没有触及剔除标准。",
      "",
      "【收录类别】",
      "1. 还能参加的空投",
      "2. 还能参加的测试网",
      "3. 还能参加的互动任务",
      "4. 还能参加的积分活动",
      "做法、时间、链接至少要有一项。",
      "",
      "【剔除标准】",
      "- 已结束的活动",
      "- 纯喊单",
      "- 没有参加方式的贴文",
      "",
      "无关闲聊、纯价格波动、重复转发不算。",
    ].join("\n"),
  },
  {
    id: "exchange-listing",
    name: "交易所上币与下架",
    prompt: [
      "判断这则消息是否为交易所的上币、开盘、下架、暂停充提或交易对变更，且没有触及剔除标准。必须点名币种或交易对。",
      "",
      "【收录类别】",
      "1. 新上币",
      "2. 开盘",
      "3. 下架",
      "4. 暂停充提",
      "5. 交易对变更",
      "以上每一项都要点名币种或交易对。",
      "",
      "【剔除标准】",
      "- 没有点名对象的泛称行情",
      "",
      "无关闲聊、纯价格波动、重复转发不算。",
    ].join("\n"),
  },
  {
    id: "scam-alert",
    name: "诈骗与安全警示",
    prompt: [
      "判断这则消息是否在警告下列安全事件，且没有触及剔除标准。必须有具体对象或手法。",
      "",
      "【收录类别】",
      "1. 诈骗",
      "2. 钓鱼",
      "3. 假空投",
      "4. 盗币",
      "5. 私钥外泄",
      "6. 恶意授权",
      "7. 合约风险",
      "以上每一项都要点名具体对象或手法。",
      "",
      "【剔除标准】",
      "- 没有对象的泛泛提醒",
      "",
      "无关闲聊、纯价格波动、重复转发不算。",
    ].join("\n"),
  },
  {
    id: "account-speaks",
    name: "{某账号}发话",
    prompt: [
      "使用者会把名称和本段里的「某账号」换成要追踪的人、公司或频道，并把「某主题」换成要听的主题。判断这则消息是否是该账号本人在发话，而且内容符合该主题，且没有触及剔除标准。",
      "",
      "【收录类别】",
      "1. 发话者就是指定的那个账号（人、公司或频道）",
      "2. 内容符合使用者写下的主题",
      "两项必须同时成立才算。",
      "",
      "【剔除标准】",
      "- 同一个聊天里其他人的发言，即使话题相同也不算",
      "- 该账号的打招呼、贴图",
      "- 该账号没有实质内容的转发",
      "",
      "无关闲聊、纯价格波动、重复转发不算。",
    ].join("\n"),
  },
  {
    id: "actionable-howto",
    name: "可照做的做法",
    prompt: [
      "判断这则消息是否包含可以照做、并且能做完一件具体事情的做法，且没有触及剔除标准。",
      "",
      "【收录类别】",
      "1. 步骤：按着做就能完成一件具体事情",
      "2. 指令：执行后就能完成一件具体事情",
      "3. 设定：改完就能完成一件具体事情",
      "4. 一条链接：打开后就能完成那件具体事情",
      "步骤、指令、设定、链接至少要有一项。",
      "",
      "【剔除标准】",
      "- 只有意见，没有做法",
      "- 纯新闻，没有做法",
      "- 没有做法的转发",
      "",
      "无关闲聊、纯价格波动、重复转发不算。",
    ].join("\n"),
  },
  {
    id: "hiring",
    name: "征人、接案或合作",
    prompt: [
      "判断这则消息是否在征人、接案或找合作，且没有触及剔除标准。必须同时点名角色或技能，以及联络方式或链接。",
      "",
      "【收录类别】",
      "1. 征人：点名职位或技能，并附上联络方式或链接",
      "2. 接案：点名要做的角色或技能，并附上联络方式或链接",
      "3. 合作：点名需要的角色或技能，并附上联络方式或链接",
      "",
      "【剔除标准】",
      "- 没有联络方式或链接的励志贴文",
      "- 没有点名角色或技能的贴文",
      "",
      "无关闲聊、纯价格波动、重复转发不算。",
    ].join("\n"),
  },
  {
    id: "tech-ai",
    name: "科技与 AI",
    prompt: [
      "判断这则消息是否是给开发者留意的最新科技或 AI 消息，而且带有新事实，且没有触及剔除标准。必须点名项目、模型、库或论文。",
      "",
      "【收录类别】",
      "1. 模型或 API 发布：点名模型或 API，并写出新事实",
      "2. 框架或编程语言发布：点名框架或语言，并写出新事实",
      "3. 开发者必须套用的安全修补：点名项目或库，并写出要修什么",
      "4. 破坏性变更：点名项目、框架或 API，并写出改了什么",
      "5. 有实际结果的重要论文或基准测试：点名论文或基准，并写出结果",
      "6. 工具停摆或恢复：点名产品，并写出停摆或恢复",
      "以上每一项都要有新事实，而且点名项目、模型、库或论文。",
      "",
      "【剔除标准】",
      "- 没有新事实的炒作",
      "- 价格讨论",
      "- 迷因币",
      "- 空泛的「AI 好厉害」",
      "- 重复转发",
      "- 无关闲聊",
      "",
      "无关闲聊、纯价格波动、重复转发不算。",
    ].join("\n"),
  },
];

const en: readonly BuiltinTaskTemplate[] = [
  {
    id: "wool",
    name: "Airdrops and perks",
    prompt: [
      "Decide whether this message fits the airdrop and perk categories below, and does not meet an exclusion.",
      "A message counts when the offer has no region restriction, or users in Asia can join; Hong Kong-only products still count because Hong Kong is in Asia; offers that exclude Asia do not count.",
      "",
      "【Inclusion categories】",
      "1. Credit / debit cards: new-card offers, high cashback, miles or points offers, annual-fee waivers",
      "2. Banks: account-opening rewards, deposit-rate offers, cross-border transfer offers",
      "3. Payment tools (Alipay/AlipayHK/WeChat Pay/Octopus/PayMe and similar): new-user offers, merchant discounts, stored-value rewards; other global or Asian payment perks also count",
      "4. Staking / holding: staking APY on major coins (BTC/ETH/SOL and similar), lock-up terms, platform trustworthiness",
      "5. Web3 fixed deposits / yield perks: CeFi/DeFi fixed-deposit products, annualized yield, platform risk rating",
      "6. Newly issued credit / debit cards (APY-style or high cashback): for example high-interest or high-cashback products issued by virtual banks and fintech cards",
      "7. eSIM / phone plans: cheap number-keeping and roaming plans with no region limit, or that Asian users can buy",
      "8. On-chain identity perks: for example whitelist or airdrop eligibility from wallet-address holding history or on-chain activity proofs (POAP and similar)",
      "9. NFT: low-price or free acquisition of projects expected to have real utility or return (not pure speculation)",
      "10. New-chain campaigns / airdrops: testnet tasks and ecosystem campaigns with no region limit, or that Asian users can join",
      "",
      "【Exclusion criteria】",
      "- Requires depositing a large sum before you qualify (high-risk setup)",
      "- DeFi protocols or exchanges that are unvetted, have been live for under 3 months, or have no audit report",
      "- Requires leaking KYC or identity-document data in exchange for a small reward",
      "- Clearly a referral-code or MLM-style reward structure (you are paid only for recruiting people)",
      "- Expired offers, or offers expiring in under 48 hours, unless specifically marked urgent",
      "",
      "Unrelated chat, bare price moves, and duplicate reposts do not count.",
    ].join("\n"),
  },
  {
    id: "crypto-major",
    name: "Major crypto news",
    prompt: [
      "Decide whether this message is major cryptocurrency news, and does not meet an exclusion.",
      "",
      "【Inclusion categories】",
      "1. A sharp move in a major coin or an important protocol",
      "2. An exchange outage or failure",
      "3. A regulation or ETF decision",
      "4. A large hack",
      "5. A depeg",
      "6. A major-chain halt",
      "",
      "【Exclusion criteria】",
      "- Small day-to-day moves",
      "- Meme-coin shilling",
      "- Reposts with no new facts",
      "",
      "Unrelated chat, bare price ticks, and duplicate reposts do not count.",
    ].join("\n"),
  },
  {
    id: "cloud-resident",
    name: "Cloud-resident perks",
    prompt: [
      "Decide whether this message is a perk or useful notice for cloud residents, it states how to claim it, and it does not meet an exclusion.",
      "",
      "【Inclusion categories】",
      "1. A discount",
      "2. Free quota",
      "3. A restock",
      "4. A referral reward",
      "5. A node",
      "6. A whitelist",
      "Each of the above counts only when the message includes a clear way to claim it.",
      "",
      "【Exclusion criteria】",
      "- Chat unrelated to cloud-resident perks",
      "- Other projects",
      "- Promotion with no way to claim",
      "",
      "Unrelated chat, bare price ticks, and duplicate reposts do not count.",
    ].join("\n"),
  },
  {
    id: "stock-directional",
    name: "{a stock}: good or bad news",
    prompt: [
      'Replace "{a stock}" in the task name and in this prompt with the ticker or company name to track. Decide whether this message is about that stock and gives either a good or a bad reason, and does not meet an exclusion.',
      "",
      "【Inclusion categories】",
      "1. Good news that names that stock: earnings, orders, policy support, increased holdings, upgrades",
      "2. Bad news that names that stock: losses, investigations, reduced holdings, downgrades, accidents, lawsuits",
      "The ticker or company name and one of those reasons must both appear.",
      "",
      "【Exclusion criteria】",
      "- Other stocks",
      "- Directionless price quotes",
      "- Unrelated market chat",
      "",
      "Unrelated chat, bare price ticks, and duplicate reposts do not count.",
    ].join("\n"),
  },
  {
    id: "airdrop-testnet",
    name: "Airdrops and testnets",
    prompt: [
      "Decide whether this message is an airdrop, testnet, interactive task, or points campaign that people can still join, and it does not meet an exclusion.",
      "",
      "【Inclusion categories】",
      "1. An airdrop people can still join",
      "2. A testnet people can still join",
      "3. An interactive task people can still join",
      "4. A points campaign people can still join",
      "It must include how to take part, a time, or a link.",
      "",
      "【Exclusion criteria】",
      "- Ended campaigns",
      "- Pure shilling",
      "- Posts with no way to join",
      "",
      "Unrelated chat, bare price ticks, and duplicate reposts do not count.",
    ].join("\n"),
  },
  {
    id: "exchange-listing",
    name: "Exchange listings and delistings",
    prompt: [
      "Decide whether this message is an exchange listing, market open, delisting, deposit or withdrawal pause, or trading-pair change, and it does not meet an exclusion. It must name the coin or pair.",
      "",
      "【Inclusion categories】",
      "1. A new listing",
      "2. A market open",
      "3. A delisting",
      "4. A deposit or withdrawal pause",
      "5. A trading-pair change",
      "Each of the above must name the coin or pair.",
      "",
      "【Exclusion criteria】",
      "- Generic market talk that names no asset",
      "",
      "Unrelated chat, bare price ticks, and duplicate reposts do not count.",
    ].join("\n"),
  },
  {
    id: "scam-alert",
    name: "Scams and security alerts",
    prompt: [
      "Decide whether this message warns about one of the security events below, and it does not meet an exclusion. It must name a specific target or method.",
      "",
      "【Inclusion categories】",
      "1. A scam",
      "2. Phishing",
      "3. A fake airdrop",
      "4. Stolen funds",
      "5. A private-key leak",
      "6. A malicious approval",
      "7. Contract risk",
      "Each of the above must name a specific target or method.",
      "",
      "【Exclusion criteria】",
      "- Vague reminders with no target",
      "",
      "Unrelated chat, bare price ticks, and duplicate reposts do not count.",
    ].join("\n"),
  },
  {
    id: "account-speaks",
    name: "{an account} speaks",
    prompt: [
      'Replace "{an account}" in the task name and in this prompt with the person, company, or channel to watch, and replace "{a topic}" with the topic you want. Decide whether this message is that account speaking, the content matches that topic, and it does not meet an exclusion.',
      "",
      "【Inclusion categories】",
      "1. The speaker is the named account (a person, company, or channel)",
      "2. The content matches the topic the user wrote",
      "Both must be true.",
      "",
      "【Exclusion criteria】",
      "- Other people in the same chat, even when the topic matches",
      "- Greetings or stickers from that account",
      "- Reposts from that account with no substance",
      "",
      "Unrelated chat, bare price ticks, and duplicate reposts do not count.",
    ].join("\n"),
  },
  {
    id: "actionable-howto",
    name: "Steps you can follow",
    prompt: [
      "Decide whether this message includes steps you can follow that finish a concrete task, and it does not meet an exclusion.",
      "",
      "【Inclusion categories】",
      "1. Steps that, if followed, finish a concrete task",
      "2. A command that, when run, finishes a concrete task",
      "3. A config that, once applied, finishes a concrete task",
      "4. One link that, when opened, finishes that concrete task",
      "At least one of steps, a command, a config, or a link must be present.",
      "",
      "【Exclusion criteria】",
      "- Opinions with no procedure",
      "- Pure news with no procedure",
      "- Reposts with no procedure",
      "",
      "Unrelated chat, bare price ticks, and duplicate reposts do not count.",
    ].join("\n"),
  },
  {
    id: "hiring",
    name: "Hiring, gigs, or collaboration",
    prompt: [
      "Decide whether this message is a job, freelance gig, or collaboration request, and it does not meet an exclusion. It must name a role or skill and include a contact or a link.",
      "",
      "【Inclusion categories】",
      "1. Hiring: names the role or skill, and includes a contact or a link",
      "2. A freelance gig: names the role or skill, and includes a contact or a link",
      "3. Collaboration: names the role or skill needed, and includes a contact or a link",
      "",
      "【Exclusion criteria】",
      "- Motivational posts with no contact or link",
      "- Posts that name no role or skill",
      "",
      "Unrelated chat, bare price ticks, and duplicate reposts do not count.",
    ].join("\n"),
  },
  {
    id: "tech-ai",
    name: "Tech and AI",
    prompt: [
      "Decide whether this message is latest technology or AI news for developers watching the field, it states a new fact, and it does not meet an exclusion. It must name a project, model, library, or paper.",
      "",
      "【Inclusion categories】",
      "1. A model or API release: names the model or API, and states a new fact",
      "2. A framework or language release: names the framework or language, and states a new fact",
      "3. A security fix developers must apply: names the project or library, and states what to fix",
      "4. A breaking change: names the project, framework, or API, and states what changed",
      "5. An important paper or benchmark with a real result: names the paper or benchmark, and states the result",
      "6. A tool outage or recovery: names the product, and states the outage or recovery",
      "Each of the above must include a new fact and name a project, model, library, or paper.",
      "",
      "【Exclusion criteria】",
      "- Hype with no new fact",
      "- Price talk",
      "- Meme-coin",
      '- Generic praise such as "AI is amazing" with no new fact',
      "- Duplicate reposts",
      "- Unrelated chat",
      "",
      "Unrelated chat, bare price ticks, and duplicate reposts do not count.",
    ].join("\n"),
  },
];

const BY_LOCALE: Record<Locale, readonly BuiltinTaskTemplate[]> = {
  "zh-Hant": zhHant,
  "zh-Hans": zhHans,
  en,
};

export function builtinTaskTemplates(locale: Locale): readonly BuiltinTaskTemplate[] {
  return BY_LOCALE[locale] ?? zhHant;
}
